const annonces =
{
    "utilisateur": {
        "nom": "John Doe",
        "age": 30,
        "email": "john.doe@example.com"
    },
    "annonces": [
        {
            idAnnonce: '1',
            idUtilisateur: '1',
            marque: 'Honda',
            modele: 'Fit',
            categorie: 'touriste',
            annee: '2018',
            date: '08/01/2024',
            prix: '54M',
            kilometrage: '40 000 km',
            carburant: 'Essence',
            transmission: 'Automatique',
            etat_mecanique: 'Entretien régulier, aucune réparation majeure Entretien régulier, aucune réparation majeure Entretien régulier, aucune réparation majeure Entretien régulier, aucune réparation majeure Entretien régulier, aucune réparation majeure',
            etat_exterieur: 'Quelques éraflures mineures',
            etat_interieur: 'Propre, non-fumeur',
            immatriculation: '1234 XXX',
            proprietaire: 'falyarivelo',
            contact: 'faly@gmail.com',
            status: 'Vendu',
            nombrePhotos: '2',
            pdp:'https://images.unsplash.com/photo-1656338997878-279d71d48f6e?q=80&w=1364&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
            photo: 'https://firebasestorage.googleapis.com/v0/b/voiture-13909.appspot.com/o/45f2d329-e49b-402d-b2c1-7d5daa809a1f.jpeg?alt=media&token=408cd76a-55bc-4454-a9e2-acef0cb3041d'
        },
        {
            idAnnonce: '2',
            idUtilisateur: '2',
            marque: 'Honda',
            modele: 'Fit',
            categorie: 'touriste',
            annee: '2018',
            date: '08/01/2024',
            prix: '54M',
            kilometrage: '40 000 km',
            carburant: 'Essence',
            transmission: 'Automatique',
            etat_mecanique: 'Entretien régulier, aucune réparation majeure',
            etat_exterieur: 'Quelques éraflures mineures',
            etat_interieur: 'Propre, non-fumeur',
            immatriculation: '1234 XXX',
            proprietaire: 'falyarivelo',
            contact: 'faly@gmail.com',
            status: 'Vendu',
            nombrePhotos: '5',
            pdp:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
            photo: 'https://images.unsplash.com/photo-1688893288248-3338b8491a46?q=80&w=1341&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'

        },
        {
            idAnnonce: '3',
            idUtilisateur: '3',
            marque: 'Honda',
            modele: 'Fit',
            categorie: 'touriste',
            annee: '2018',
            date: '08/01/2024',
            prix: '54M',
            kilometrage: '40 000 km',
            carburant: 'Essence',
            transmission: 'Automatique',
            etat_mecanique: 'Entretien régulier, aucune réparation majeure',
            etat_exterieur: 'Quelques éraflures mineures',
            etat_interieur: 'Propre, non-fumeur',
            immatriculation: '1234 XXX',
            proprietaire: 'falyarivelo',
            contact: 'faly@gmail.com',
            status: 'Vendu',
            nombrePhotos: '5',
            pdp:'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
            photo: 'https://images.unsplash.com/photo-1669730240702-0037bad42a9f?q=80&w=1335&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
        },
        {
            idAnnonce: '3',
            idUtilisateur: '3',
            marque: 'Honda',
            modele: 'Fit',
            categorie: 'touriste',
            annee: '2018',
            date: '08/01/2024',
            prix: '54M',
            kilometrage: '40 000 km',
            carburant: 'Essence',
            transmission: 'Automatique',
            etat_mecanique: 'Entretien régulier, aucune réparation majeure',
            etat_exterieur: 'Quelques éraflures mineures',
            etat_interieur: 'Propre, non-fumeur',
            immatriculation: '1234 XXX',
            proprietaire: 'falyarivelo',
            contact: 'faly@gmail.com',
            status: 'Vendu',
            nombrePhotos: '5',
            pdp:'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?q=80&w=1335&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 
            photo: 'https://images.unsplash.com/photo-1577372794873-e6b8efa7dcc3?q=80&w=1430&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
        }
    ]
}
    ;

export default annonces;